version: '3'
services:
  db:
    hostname: percona-common-db
    image: percona mysql:8
    volumes:
      - ./mounts/db_data:/var/lib/postgresql/data
    environment:
      Mysql_USER: <PG_USER>
      Mysql_PASSWORD: <PG_PASSWORD>
      Mysql_DB: stockerize_prod
    ports:
      - 3306:3306
    restart: unless-stopped
  app1:
    hostname: appserver1.com
    build: ./app1
    ports:
      - "5001:5000"
    depends_on:
     - db
  app2:
    hostname: appserver2.com
    build: ./app2
    ports:
      - "5002:5000"
    depends_on:
     - db
  lb:
  build: ./nginx
  ports:
    - "8080:80"
  depends_on:
    - app1
    - app2
  
